
export const GET_ADVERTISING = 'GET_ADVERTISING'
export const GET_ITEMS = 'GET_ITEMS'
export const GET_SINGLE_ITEM = 'GET_SINGLE_ITEM'
export const GET_SEARCH_ITEM = 'GET_SEARCH_ITEM'
export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const DELETE__BASKET = 'DELETE__BASKET'
export const GET_TIMER = 'GET_TIMER'
export const SORT_ITEMS = 'SORT_ITEMS'
export const GET_PROFILE = 'GET_PROFILE'